### ISSUE TITLE
official x3dom dist repo

### ISSUE THREAD

**Issue by fibo** [despairblue/bower-x3dom#2]
Hi,

there is a [x3dom/dist](https://github.com/x3dom/dist) repo to publish it on npm and bower, I asked in this issue https://github.com/x3dom/x3dom/issues/592.

Since your package is already registered on bower, I cannot register x3dom/dist, can you please ask to join the repo, or let me register it as x3dom (or whatever you think it makes sense)?

Thank you in advance,
Gianluca.

**Comment by despairblue** [comment]
I unregistered it, I'll probably use the npm package instead, so I wouldn't be a good fit for maintaining the bower package :wink: 

I don't know how many people use the package, so it would be good if it is reregistered as soon as possible. 

Thank you for taking the time to package x3dom for npm!

**Comment by fibo** [comment]
Thanks, was just registered.
